"""Add phone number column to users table

Revision ID: 275b790e940c
Revises: 1a04f4c2ac02
Create Date: 2021-12-20 09:33:29.685017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275b790e940c'
down_revision = '1a04f4c2ac02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
